using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Stoogebag.ManagedUpdate.SourceGeneration
{
    [Generator]
    public class ManagedUpdateSourceGenerator : ISourceGenerator
    {
        private const string Namespace = "Stoogebag.ManagedUpdate";
        private const string GeneratedNamespace = "Stoogebag.ManagedUpdate.Generated";

        public void Initialize(GeneratorInitializationContext context) { }

        public void Execute(GeneratorExecutionContext context)
        {
            var compilation = context.Compilation;

            var iUpdate = compilation.GetTypeByMetadataName($"{Namespace}.IManagedUpdate");
            var iFixed = compilation.GetTypeByMetadataName($"{Namespace}.IManagedFixedUpdate");
            var iLate = compilation.GetTypeByMetadataName($"{Namespace}.IManagedLateUpdate");
            var monoBehaviour = compilation.GetTypeByMetadataName("UnityEngine.MonoBehaviour");

            if (monoBehaviour == null) return;
            if (iUpdate == null && iFixed == null && iLate == null) return;

            var managedTypes = new List<INamedTypeSymbol>();

            foreach (var syntaxTree in compilation.SyntaxTrees)
            {
                var semanticModel = compilation.GetSemanticModel(syntaxTree);
                var root = syntaxTree.GetRoot();

                foreach (var classDecl in root.DescendantNodes().OfType<ClassDeclarationSyntax>())
                {
                    var symbol = semanticModel.GetDeclaredSymbol(classDecl) as INamedTypeSymbol;
                    if (symbol == null) continue;
                    if (symbol.IsAbstract) continue;
                    if (!InheritsFrom(symbol, monoBehaviour)) continue;

                    if (Implements(symbol, iUpdate) ||
                        Implements(symbol, iFixed) ||
                        Implements(symbol, iLate))
                    {
                        managedTypes.Add(symbol);
                    }
                }
            }

            if (managedTypes.Count == 0) return;

            var source = GenerateSource(managedTypes, iUpdate, iFixed, iLate);
            context.AddSource("ManagedUpdateTypeRegistration.g.cs", source);
        }

        private static bool InheritsFrom(INamedTypeSymbol symbol, INamedTypeSymbol baseType)
        {
            var current = symbol.BaseType;
            while (current != null)
            {
                if (SymbolEqualityComparer.Default.Equals(current, baseType))
                    return true;
                current = current.BaseType;
            }
            return false;
        }

        private static bool Implements(INamedTypeSymbol symbol, INamedTypeSymbol? interfaceType)
        {
            if (interfaceType == null) return false;
            return symbol.AllInterfaces.Contains(interfaceType, SymbolEqualityComparer.Default);
        }

        private static string GenerateSource(
            List<INamedTypeSymbol> types,
            INamedTypeSymbol? iUpdate,
            INamedTypeSymbol? iFixed,
            INamedTypeSymbol? iLate)
        {
            var sb = new StringBuilder();

            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine($"using {Namespace};");
            sb.AppendLine("using UnityEngine;");
            sb.AppendLine();

            var assemblyName = SanitizeIdentifier(types[0].ContainingAssembly?.Name ?? "Assembly");
            sb.AppendLine($"namespace {GeneratedNamespace}");
            sb.AppendLine("{");

            GenerateRegistrationClass(sb, types, assemblyName);

            foreach (var type in types)
                GenerateManager(type, sb, iUpdate, iFixed, iLate);

            sb.AppendLine("}");

            return sb.ToString();
        }

        private static void GenerateRegistrationClass(StringBuilder sb, List<INamedTypeSymbol> types, string assemblyName)
        {
            sb.AppendLine($"    public static class ManagedUpdateTypeRegistration_{assemblyName}");
            sb.AppendLine("    {");
            sb.AppendLine("        [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.BeforeSceneLoad)]");
            sb.AppendLine("        public static void Register()");
            sb.AppendLine("        {");

            foreach (var type in types)
            {
                var fullName = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                var managerName = GetManagerName(type);
                sb.AppendLine($"            ManagedUpdateTypeMap.Register(typeof({fullName}), () => new {managerName}());");
            }

            sb.AppendLine("        }");
            sb.AppendLine("    }");
        }

        private static void GenerateManager(
            INamedTypeSymbol type,
            StringBuilder sb,
            INamedTypeSymbol? iUpdate,
            INamedTypeSymbol? iFixed,
            INamedTypeSymbol? iLate)
        {
            var fullName = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var managerName = GetManagerName(type);

            bool hasUpdate = Implements(type, iUpdate);
            bool hasFixed = Implements(type, iFixed);
            bool hasLate = Implements(type, iLate);

            sb.AppendLine();
            sb.AppendLine($"    public sealed class {managerName} : ManagerBase");
            sb.AppendLine("    {");
            sb.AppendLine($"        private readonly List<{fullName}> _items = new List<{fullName}>();");
            sb.AppendLine();

            sb.AppendLine("        public override void Add(MonoBehaviour obj)");
            sb.AppendLine("        {");
            sb.AppendLine($"            if (obj is {fullName} cast) _items.Add(cast);");
            sb.AppendLine("        }");
            sb.AppendLine();

            sb.AppendLine("        public override void Remove(MonoBehaviour obj)");
            sb.AppendLine("        {");
            sb.AppendLine($"            if (obj is {fullName} cast) _items.Remove(cast);");
            sb.AppendLine("        }");

            GenerateBucketMethod(sb, hasUpdate, "Update", "ManagedUpdate");
            GenerateBucketMethod(sb, hasFixed, "FixedUpdate", "ManagedFixedUpdate");
            GenerateBucketMethod(sb, hasLate, "LateUpdate", "ManagedLateUpdate");

            sb.AppendLine("    }");
        }

        private static void GenerateBucketMethod(StringBuilder sb, bool hasBucket, string bucketName, string methodName)
        {
            sb.AppendLine();
            sb.AppendLine($"        public override void {bucketName}()");
            sb.AppendLine("        {");

            if (hasBucket)
            {
                sb.AppendLine("            for (int i = _items.Count - 1; i >= 0; i--)");
                sb.AppendLine("            {");
                sb.AppendLine("                var item = _items[i];");
                sb.AppendLine("                if (item == null) { _items.RemoveAt(i); continue; }");
                sb.AppendLine($"                item.{methodName}();");
                sb.AppendLine("            }");
            }

            sb.AppendLine("        }");
        }

        private static string GetManagerName(INamedTypeSymbol type)
        {
            var name = type.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat)
                .Replace(".", "_")
                .Replace("<", "_")
                .Replace(">", "_");
            return $"{name}ManagedUpdateManager";
        }

        private static string SanitizeIdentifier(string name)
        {
            var sb = new StringBuilder();
            foreach (var c in name)
            {
                if (char.IsLetterOrDigit(c) || c == '_')
                    sb.Append(c);
                else
                    sb.Append('_');
            }
            return sb.ToString();
        }
    }
}
